language: go

go:
  - 1.7
  - master

before_install:
  - mkdir $GOPATH/bin

install:
  - go get github.com/stretchr/testify/assert
  - curl https://glide.sh/get | sh

script:
  - make vendor
  - make check
